name: Java Build with Gradle

on:
  push:
    branches:
      - main # Change this to your main branch name, if different
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 'adopt@1.11' # Change this to your desired Java version

    - name: Build with Gradle
      run: |
        ./gradlew build --no-daemon

    - name: Test
      run: |
        ./gradlew test --no-daemon
